In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [37]:
vocab_size = 50

In [38]:
onehot_v = [one_hot(words, vocab_size) for words in sent]
onehot_v

[[9, 25, 7, 31],
 [9, 25, 7, 45],
 [9, 10, 7, 43],
 [23, 11, 45, 42, 26],
 [23, 11, 45, 42, 16],
 [11, 9, 17, 7, 32],
 [39, 17, 43, 42]]

In [39]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [40]:
senLen = 5
embedded_docs = pad_sequences(onehot_v, padding = 'post', maxlen = senLen)
print(embedded_docs)

[[ 9 25  7 31  0]
 [ 9 25  7 45  0]
 [ 9 10  7 43  0]
 [23 11 45 42 26]
 [23 11 45 42 16]
 [11  9 17  7 32]
 [39 17 43 42  0]]


In [46]:
dim = 10

In [47]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length = senLen))
model.compile('adam', 'mse')
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 5, 10)             500       
                                                                 
Total params: 500
Trainable params: 500
Non-trainable params: 0
_________________________________________________________________


In [43]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 45ms/step
[[[-6.9627538e-03 -6.5797083e-03]
  [-1.7202746e-02 -2.9778421e-02]
  [ 3.9511394e-02 -4.5876574e-02]
  [ 3.3964101e-02  2.7240228e-02]
  [-4.3586876e-02 -4.7925569e-02]]

 [[-6.9627538e-03 -6.5797083e-03]
  [-1.7202746e-02 -2.9778421e-02]
  [ 3.9511394e-02 -4.5876574e-02]
  [-2.8462565e-02  3.1530034e-02]
  [-4.3586876e-02 -4.7925569e-02]]

 [[-6.9627538e-03 -6.5797083e-03]
  [ 2.2567809e-05  4.7254030e-02]
  [ 3.9511394e-02 -4.5876574e-02]
  [ 2.4751630e-02 -1.1904202e-02]
  [-4.3586876e-02 -4.7925569e-02]]

 [[ 3.8487744e-02  3.1882595e-02]
  [-1.6236089e-02  3.2746401e-02]
  [-2.8462565e-02  3.1530034e-02]
  [ 1.9220863e-02 -3.9199840e-02]
  [ 3.4347627e-02 -6.3290447e-04]]

 [[ 3.8487744e-02  3.1882595e-02]
  [-1.6236089e-02  3.2746401e-02]
  [-2.8462565e-02  3.1530034e-02]
  [ 1.9220863e-02 -3.9199840e-02]
  [ 4.2913903e-02 -1.6997539e-02]]

 [[-1.6236089e-02  3.2746401e-02]
  [-6.9627538e-03 -6.5797083e-03]
  [-7.2787032e-03  6